steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy', 'hello_world',
      '--region=us-central1',
      '--runtime=python310',
      '--trigger-http',
      '--allow-unauthenticated',
      '--entry-point=hello_world',
      '--source=.'
    ]
options:
  logging: CLOUD_LOGGING_ONLY
